<script setup lang="ts">
useSeoMeta({title:'Conseils pour envoyer vos colis en Afrique | WefretAfrica',description:'Guides pratiques sur le fret aérien et maritime entre la France, Lomé et Cotonou.'})
useHead({link:[{rel:'canonical',href:'https://www.wefretafrica.com/blog'}]})
const articles=[
  {tag:'Tarifs',title:'Combien coûte un envoi de colis de France vers le Togo ?',text:'Les critères qui déterminent le prix et les informations à préparer pour obtenir un devis précis.',link:'/prix-envoi-colis-france-togo',image:'/blog-prix-france-togo.webp'},
  {tag:'Réglementation',title:'Quels produits sont interdits dans un colis ?',text:'Les marchandises à signaler ou à éviter avant un transport aérien ou maritime.',link:'/produits-interdits-colis-afrique',image:'/blog-produits-interdits.webp'},
  {tag:'Délais',title:'Combien de temps prend une livraison vers le Togo ou le Bénin ?',text:'Comprenez les délais indicatifs et ce qui peut influencer la date de réception.',link:'/delai-livraison-togo-benin',image:'/blog-delais-togo-benin.webp'},
  {tag:'Calcul',title:'Comment calculer le poids volumétrique ?',text:'Une méthode simple pour mieux estimer le tarif de votre colis en fret aérien.',link:'/calcul-poids-volumetrique',image:'/blog-poids-volumetrique.webp'},
  {tag:'Guide',title:'Fret aérien ou maritime : comment choisir ?',text:'Comparez délai, volume et budget pour sélectionner le transport adapté à votre colis.',link:'/fret-aerien',image:'/blog-fret-aerien-maritime.webp'},
  {tag:'Préparation',title:'Bien préparer un colis pour le fret maritime',text:'Emballage, étiquetage et informations utiles : les réflexes avant la collecte.',link:'/fret-maritime',image:'/blog-preparer-colis-maritime.webp'},
  {tag:'Destination',title:'Envoyer un colis de Paris à Lomé',text:'Les étapes essentielles, de l’enlèvement en Île-de-France à la réception au Togo.',link:'/envois-colis-paris-lome',image:'/blog-colis-paris-lome.webp'},
  {tag:'Destination',title:'Organiser un envoi de Paris à Cotonou',text:'Aérien ou maritime, découvrez la solution adaptée à votre expédition vers le Bénin.',link:'/envois-colis-paris-cotonou',image:'/blog-colis-paris-cotonou.webp'}
]
</script>
<template><main><SiteHeader /><section class="blog-hero"><p class="kicker">Le journal WefretAfrica</p><h1>Conseils pour envoyer <em>sans stress</em></h1><p>Des réponses simples pour préparer, expédier et suivre vos colis entre la France et l’Afrique de l’Ouest.</p></section><section class="section"><div class="article-grid"><NuxtLink v-for="article in articles" :key="article.title" :to="article.link" class="article-card"><img :src="article.image" :alt="article.title" loading="lazy" decoding="async"><div><span>{{article.tag}}</span><h2>{{article.title}}</h2><p>{{article.text}}</p><b>Lire le guide →</b></div></NuxtLink></div></section><section class="cta"><h2>Une question sur votre <em>propre colis ?</em></h2><NuxtLink class="btn white" to="/devis-en-ligne">Parler à l’équipe →</NuxtLink></section><footer><div class="brand"><img src="/logo.png" alt=""><b>WeFret<span>Africa</span></b></div><p>Votre partenaire pour l’envoi de colis entre la France et l’Afrique de l’Ouest.</p><small>© 2026 WefretAfrica. Tous droits réservés.</small></footer></main></template>
